baseURL = "https://elrhedda.net"
title = "Ahmed El Rheddane"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "elrhedda"
googleAnalytics = "UA-108617261-1"

Paginate = 7
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Fellow human being with a Ph.D."
title404 = "Hic sunt castores!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Ahmed El Rheddane"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "-"

[params.social]
email = "ahmed[AT]elrhedda[DOT]net"
facebook = "elrhedda"
github = "elrhedda"
linkedin = "elrhedda"
twitter = "elrhedda"

[params.social.config]
platforms = ["email","github","linkedin","facebook","twitter"]

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"

[permalinks]
page = "/:slug/"
blog = "/:year/:month/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
